import { StudentCampus } from "./Scrapper";

export const campusData: StudentCampus[] = [
  {
    cityId: "BDX",
    cityName: "Bordeaux",
    countryId: "FR",
    countryName: "France",
    lat: 44.837789,
    lon: -0.57918,
  },
  {
    cityId: "RUN",
    cityName: "Reunion",
    countryId: "RE",
    countryName: "Réunion",
    lat: -21.115141,
    lon: 55.536384,
  },
  {
    cityId: "LIL",
    cityName: "Lille",
    countryId: "FR",
    countryName: "France",
    lat: 50.62925,
    lon: 3.057256,
  },
  {
    cityId: "LYN",
    cityName: "Lyon",
    countryId: "FR",
    countryName: "France",
    lat: 45.76342,
    lon: 4.834277,
  },
  {
    cityId: "MAR",
    cityName: "Marseille",
    countryId: "FR",
    countryName: "France",
    lat: 43.296482,
    lon: 5.36978,
  },
  {
    cityId: "MPL",
    cityName: "Montpellier",
    countryId: "FR",
    countryName: "France",
    lat: 43.61092,
    lon: 3.87723,
  },
  {
    cityId: "MLN",
    cityName: "Moulins",
    countryId: "FR",
    countryName: "France",
    lat: 46.566667,
    lon: 3.333333,
  },
  {
    cityId: "MLH",
    cityName: "Mulhouse",
    countryId: "FR",
    countryName: "France",
    lat: 47.750839,
    lon: 7.335888,
  },
  {
    cityId: "NCY",
    cityName: "Nancy",
    countryId: "FR",
    countryName: "France",
    lat: 48.692055,
    lon: 6.184417,
  },
  {
    cityId: "NAN",
    cityName: "Nantes",
    countryId: "FR",
    countryName: "France",
    lat: 47.218102,
    lon: -1.5528,
  },
  {
    cityId: "NCE",
    cityName: "Nice",
    countryId: "FR",
    countryName: "France",
    lat: 43.70313,
    lon: 7.26608,
  },
  {
    cityId: "PAR",
    cityName: "Paris",
    countryId: "FR",
    countryName: "France",
    lat: 48.856614,
    lon: 2.352222,
  },
  {
    cityId: "REN",
    cityName: "Rennes",
    countryId: "FR",
    countryName: "France",
    lat: 48.11198,
    lon: -1.67429,
  },
  {
    cityId: "STG",
    cityName: "Strasbourg",
    countryId: "FR",
    countryName: "France",
    lat: 48.58392,
    lon: 7.74553,
  },
  {
    cityId: "TLS",
    cityName: "Toulouse",
    countryId: "FR",
    countryName: "France",
    lat: 43.6045,
    lon: 1.444,
  },
  {
    cityId: "BAR",
    cityName: "Barcelona",
    countryId: "ES",
    countryName: "Spain",
    lat: 41.390205,
    lon: 2.154007,
  },
  {
    cityId: "BER",
    cityName: "Berlin",
    countryId: "DE",
    countryName: "Germany",
    lat: 52.520008,
    lon: 13.404954,
  },
  {
    cityId: "BRU",
    cityName: "Brussels",
    countryId: "BE",
    countryName: "Belgium",
    lat: 50.85045,
    lon: 4.34878,
  },
  {
    cityId: "COT",
    cityName: "Cotonou",
    countryId: "BJ",
    countryName: "Benin",
    lat: 6.379448,
    lon: 2.451324,
  },
  {
    cityId: "MAD",
    cityName: "Madrid",
    countryId: "ES",
    countryName: "Spain",
    lat: 40.416775,
    lon: -3.70379,
  },
];
