name: CI/CD

on:
    push:
      branches:
        - main
        - develop
      tags:
        - 'v*'
    pull_request:
      branches:
        - main
        - develops

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '21'

            - name: Install dependencies
              run: yarn install

            - name: Run tests
              run: yarn coverage


    release:
        runs-on: ubuntu-latest
        needs: build-and-test
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        steps:
            - uses: actions/checkout@v4

            - name: Build
              run: yarn build

            - name: Create zip release
              run: zip -r hub-reworked.zip dist/ manifest.json

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  files: hub-reworked.zip
                  tag_name: ${{ github.ref }}
                  release_name: ${{ github.ref }}
                  body: "Hub Reworked - Release ${{ github.ref }}"
                  draft: false
                  prerelease: false